### ISSUE TITLE
Can't select scheme from favorites panel

### ISSUE THREAD

**Issue by alextegelid** [benweier/Schemr#26]
Pressing `[ENTER]` in the favorites panel has stopped working lately.

**Comment by benweier** [comment]
Hi @alextegelid when did it stop working for you? Does the favourites panel stay open after hitting enter or does it close and nothing happen? Is there a message displayed in the console after selecting a favourite?

**Comment by alextegelid** [comment]
I noticed it about a month ago. It's hard to be more specific since I don't switch themes very often.

The panel closes and the only line that appears in the console is this:
`reloading Packages/User/SchemrFavorites.sublime-settings`

I've recorded the bug here: http://cl.ly/0P0E1L0x1e3a
(Note that I use this in my preferences: `"schemr_preview_selection": false`)
When the panel disappears in the video, that's me hitting enter

**Comment by benweier** [comment]
@alextegelid I've been unable to reproduce this issue on OS X and Windows. Which version of ST are you using?

**Comment by alextegelid** [comment]
That's weird. I'm on the stable channel, build 3083. 
Is there any files I need to remove other than removing Schemr via Package Control to try a fresh install?

**Comment by benweier** [comment]
@alextegelid I've tested using build 3083 and found the issue. Due to the proxy I'm on at the moment I'll push the fix in a couple hours when I have a chance to switch network.

**Comment by alextegelid** [comment]
Great! Will the update be available via package control or do I need to clone the repo?

**Comment by benweier** [comment]
It will hit Package Control in the next couple hours. Let me know if you have any problems

**Comment by alextegelid** [comment]
Thanks, it works like a charm. Good job!
