### ISSUE TITLE
Schemr considers ColorSublime cached data as valid selections

### ISSUE THREAD

**Issue by stdedos** [benweier/Schemr#30]
After installing a handful of themes using Colorsublime, I wanted to review some favorites.
While doing that, I noticed that cached data from the Colorsublime make it to the rotation list

![screenshot 2016-02-09 16 16 22](https://cloud.githubusercontent.com/assets/133706/12918650/b915837c-cf48-11e5-8149-4058002e5903.png)

Would you consider an "ignore folder" option?

**Comment by benweier** [comment]
Thanks @stdedos I wasn't aware of ColorSublime. It's a good suggestion!

**Comment by benweier** [comment]
Fixed
