### ISSUE TITLE
How to disable Color Highlighter schemes at list of schemes?

### ISSUE THREAD

**Issue by Kristinita** [benweier/Schemr#34]
I run command `schemr_list_schemes` → in quick panel are many doubles due to Color Highlighter schemes. How to disable all Color Highlighter schemes?

I read [this](https://github.com/benweier/Schemr#note-about-sublimelinter-and-color-highlighter) section, but I not find, how I can disable Color Highlighter schemes.

Thanks.

**Comment by benweier** [comment]
Thanks @Kristinita, I'll take a look and see if something is going wrong with the scheme filtering

**Comment by benweier** [comment]
@Kristinita This should now be resolved so let me know if it doesn't work once the update hits Package Control.
